name: 'Github Tag Bump'
description: 'Bump and push git tag on merge'
author: 'Nick Sjostrom'
runs:
  using: 'docker'
  image: 'Dockerfile'
outputs:
  new_tag:
    description: 'The value of the newly created tag.'
  new_version:
    description: 'The value of the newly created tag without the prefix.'
  tag:
    description: 'The value of the tag before running this action.'
  version:
    description: 'The value of the tag before running this action without the prefix.'
  part:
    description: 'The part of version which was bumped.'
branding:
  icon: 'git-merge'  
  color: 'purple'
